//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeSegundaUnidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class registroDaLavagem
    {
        public System.Guid id { get; set; }
        public string cpfDoFuncionario { get; set; }
        public Nullable<System.DateTimeOffset> datadalavagem { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string tipo { get; set; }
        public Nullable<double> valorcobrado { get; set; }
        public Nullable<System.Guid> idfuncionario { get; set; }
        public Nullable<System.Guid> idveiculo { get; set; }
    
        public virtual funcionario funcionario { get; set; }
        public virtual veiculo veiculo { get; set; }

        public string DataLavagemFormatada => datadalavagem.Value.ToString("dd/MM/yyyy");
    }
}
